### PR TITLE
Handle cam track ended event

### PR DESCRIPTION
**Pull request by pnts-se-whereby**
### Description

**Summary:**
* monitor cam track for ended event
* set delay for turning of cam to 0 ms when disabling cam and the track has ended

**Related Issue:**

### Checklist

-   [x] My code follows the project's coding standards.
-   [x] Prefixed the PR title and commit messages with the service or package name
-   [ ] I have written unit tests (if applicable).
-   [ ] I have updated the documentation (if applicable).
-   [x] By submitting this pull request, I confirm that my contribution is made
        under the terms of the MIT license.

### CODE REVIEW

**Comment by kevinwhereby** [comment]
same testing instructions as this one?
https://github.com/whereby/pwa/pull/4121

**Comment by pnts-se-whereby** [comment]
> same testing instructions as this one? [whereby/pwa#4121](https://github.com/whereby/pwa/pull/4121)
Yes.

**Review by kevinwhereby — APPROVED** [review]
Works as described in PWA 🚀

**Pull request merged**
